# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    top.lctr.naive.file.system: warn
    org.springframework: warn

# Spring配置
spring:
  profiles:
    active: @env@-@os@
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      minIdle: 2
      webStatFilter:
        enabled: false
      statViewServlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: false
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # json配置
  jackson:
    mapper:
      # 接口反序列化参数时大小写不敏感
      accept-case-insensitive-properties: true
  # redis 配置
  redis:
    # 地址
    host: ENC(BDCSPs+7epG4jtog4CGZUGYJXji44cJh)
    # 端口
    port: 6379
    # 数据库索引
    database: 4
    # 密码
    password: ENC(ukDfIf5dhlbi/a8gRjHbj0MbLsvmgnM27hX+kuNon3I=)
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/strings

#服务配置
service:
  #服务标识
  key: 00000000-0000-0000-0000-000000000004
  #服务名称
  name: Java微信服务
  #版本号
  version: 1.0.0
  #启用swagger
  enableSwagger: false
  #站点资源文件根目录路径
  wwwRootDirectory: wwwroot

#项目拓展
project:
  extension:
    wechat:
      #当前服务器的根地址
      rootUrl: http://localhost:8080
      #默认的公众号名称
      mp: master
      #默认的商户号名称
      pay: master
      #默认启用微信终端服务
      enableMpEndpointServlet: true
      #默认启用微信网页授权服务
      enableOAuth2Servlet: true
      #默认启用微信收付通通知服务
      enablePayNotifyServlet: true
      #多公众号配置
      multiMp:
        #默认公众号
        master:
          #启用
          enable: true
          #公众账号标识
          appId: ENC(msaKT5SHEgfjzcPsKFrw97NMlnye/ZgW8XMEqYYdX1A=)
          #公众账号密钥
          appSecret: ENC(dN051J9in9rY/RMPpuiXT+zSvM5vk6KC0YYqCGQivlIS2gXHEUAJ2xmQRNuz/tCH)
          #令牌
          token: ENC(Yf6Wd1NhDym9ZqoyWeVR15P5rc5a14PVY7IiEL4xPB50XwFWIEfqyvsajb5sdDCv)
          #AES加密密钥
          aesKey: ENC(H4ZNsKZmGrjDPH3W+exHg/KxxkxszRiQoL3mpXjw7Ra2zvQtHf0uDJuBVR1cW3ap5JyiKDpd9fI=)
          #启用微信终端服务
          enableMpEndpointServlet: true
          #微信客户端终端的接口
          mpEndpointUrl: /wechat/endpoint

jasypt:
  encryptor:
    password: ${JAVA_LCTR_TEST_JASYPT_PASSWORD}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator