# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    top.lctr.naive.wechat.service: debug
    org.springframework: warn

# Spring配置
spring:
  profiles:
    active: @env@-@os@
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      minIdle: 2
      webStatFilter:
        enabled: false
      statViewServlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: false
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # json配置
  jackson:
    mapper:
      # 接口反序列化参数时大小写不敏感
      accept-case-insensitive-properties: true
  # redis 配置
  redis:
    # 地址
    host: ENC(BDCSPs+7epG4jtog4CGZUGYJXji44cJh)
    # 端口
    port: 6379
    # 数据库索引
    database: 4
    # 密码
    password: ENC(ukDfIf5dhlbi/a8gRjHbj0MbLsvmgnM27hX+kuNon3I=)
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/strings

#服务配置
service:
  #服务标识
  key: 00000000-0000-0000-0000-000000000004
  #服务名称
  name: Java微信服务
  #版本号
  version: 1.0.0
  #启用swagger
  enableSwagger: false
  #反向代理地址
  pathMapping:
  #站点资源文件根目录路径
  wwwRootDirectory: wwwroot

#微信公众号配置
mp:
  #消息处理模块
  message:
    #启用
    enable: true
    #线程池大小
    threadPoolSize: -1

#项目拓展
project:
  extension:
    mybatis:
      # 默认的数据源
      dataSource: master
      # mybatis配置文件路径
      configLocation: classpath:mybatis/mybatis-config.xml
      # 需要扫描的存放实体类的包（包括TypeAliasesPackage）
      scanEntitiesPackages: top.lctr.naive.wechat.service.entity.**
      # 需要扫描的存放Mapper接口类的包（可选）
      #      scanMapperPackages: project.extension.mybatis.edge.mapper.**
      # 需要扫描的存放Mapper配置类的包
      #      scanMapperXmlLocations: classpath:mybatis/mapper/**/*Mapper.xml
      # 默认的实体类表明/列名命名规则
      nameConvertType: CamelCaseToPascalCase
      # 多数据源配置
      multiDataSource:
        #主库
        master:
          enable: true
          dbType: JdbcMariaDB10
          nameConvertType: PascalCaseToUnderscoreWithLower
          properties:
            # 连接字符串
            url: ENC(et5WyCyB+Tg7q3HtouiIY57he/JUZthYE/xzHFhK/VF35puvAo+3gxR2VxAibH7F+B2ZSsLvDHc5hH8M3LlzkgkEAhmh676UG6tnso1Av+CfElXdcEJTc7pwIXDqwBBgWKEw/MaTwXx3Hwmnfq9MPFtqTzuT8AXmI5IuzRAD8Eju6hAaL2JD3G9WfkBgQfe5OPJfjzvg65HSbx4KuCs+cj/1OReS8mj0tX9SABMgo57kKzG4ytcpAwXejOIGay86FXhS7uV7zZw=)
            # 用户名
            username: ENC(LWfGadRuyaYT3ZIEFoEs/w==)
            # 密码
            password: ENC(Q88XTJSttazzBLg5bVN32Oyn0e5CagP/+MXtmSUYGxc=)
    wechat:
      #当前服务器的根地址
      rootUrl: ENC(f/3LzDYtp1JHBvfWC5+oNu9xb22RBCSH/VvX+YCYavs=)
      #默认的公众号名称
      mp: master
      #默认启用微信终端服务
      enableMpEndpointServlet: true
      #默认启用微信网页授权服务
      enableOAuth2Servlet: true
      #默认启用微信收付通通知服务
      enablePayNotifyServlet: true
      #多公众号配置
      multiMp:
        #默认公众号
        master:
          #启用
          enable: true
          #公众账号标识
          appId: ENC(XAOpIx+nd8M1KwCFPBQblFDkdh8XQ6xEjf2ZHY4Trys=)
          #公众账号密钥
          appSecret: ENC(SUgnL0Yuk0wDz3AWPKyRC+CDoap4Omu0DG4BNnf/N/j16f2RN2yl5W1s6B34cplk)
          #令牌
          token: ENC(EuptQrmInSt/IkMy3azTjWkOkiswNCcpemW/KUySWQMW7+8XMGZd+bxXwKkrs2tZ)
          #AES加密密钥
          aesKey: ENC(h0rixmhU2SrV4zQu68CrCnqdjcRARmWRX0OySwo+duyIR4siYZGiIOJ3bvwRp0LgKqZCksHfwvw=)
          #启用微信终端服务
          enableMpEndpointServlet: true
          #微信客户端终端的接口
          mpEndpointUrl: ENC(0n/JBZRJQ5q9HSUQ6VWNsdj+DiLsuz8xaC1bquVyQ64=)

jasypt:
  encryptor:
    password: ${JAVA_LCTR_TEST_JASYPT_PASSWORD}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator