# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /

# 日志配置
logging:
  level:
    top.lctr.naive.wechat.service: warn
    org.springframework: warn

#服务配置
service:
  #启用swagger
  enableSwagger: true
  #反向代理地址
  pathMapping: /api
  #站点资源文件根目录路径
  wwwRootDirectory: /app-data/naive-wechat-service/wwwroot

#项目拓展
project:
  extension:
    wechat:
      #当前服务器的根地址
      rootUrl: ENC(z+Pfbiiy4SxtBGPXNmFDrqzhdrlqRONQbU1j6jtOXLWAGWRjhYx+NQ==)