# 日志配置
logging:
  level:
    top.lctr.naive.wechat.service: warn
    org.springframework: warn

#服务配置
service:
  #启用swagger
  enableSwagger: false

#项目拓展
project:
  extension:
    wechat:
      #当前服务器的根地址
      rootUrl: https://wechat.lctr.top